Add an option to create parent item from identifier
zotero/zotero pull request #1901
Opened 2020-10-13 20:55 UTC by fletcherhaz

2020-10-15 05:29 UTC, dstillman requested changes
This is great, but trying this out, I don't think we should have both "Create Parent Item" and "Create Parent Item from Identifier". We should just have a single "Create Parent Item…" option that lets you enter an identifier, with a primary "Add Item" (or something) button in the bottom right and secondary "Manual Entry" button in the bottom left. This will help convey that you really shouldn't enter data manually when you have a choice.

Also, as nice as it is to reuse the lookup panel as is, we really shouldn't suggest that you can enter multiple identifiers, so we need an alternative version of the caption text without plural identifiers.

2020-10-15 05:29 UTC, dstillman commented on chrome/content/zotero/lookup.js
> +				Zotero_Lookup.accept(textBox, this.childItem ? { ...this.childItem } : false);
Why destructure instead of just passing `this.childItem`?

2020-10-15 05:29 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +				id: item.id
Can't we just pass `item` here as `childItem`, store the actual item, and get the libraryID and collections from that in Zotero_Lookup?

2020-10-15 05:29 UTC, dstillman commented on chrome/content/zotero/zoteroPane.xul
> +					<menuitem class="menuitem-iconic zotero-menuitem-create-parent-from-identifier" label="&zotero.items.menu.parentFromIdentifier;" oncommand="ZoteroPane_Local.createParentItemFromIdentifier(this.p
Just `ZoteroPane` is fine. (`ZoteroPane_Local` is an old thing.)

2020-10-15 05:29 UTC, dstillman commented on chrome/locale/en-US/zotero/zotero.dtd
> +<!ENTITY zotero.items.menu.parentFromIdentifier             "Create Parent Item From Identifier">
Lowercase `from` is house title-case style

2020-10-27 16:50 UTC, fletcherhaz commented
@dstillman I reworked this. Could you take a look at this and let me know what you think?

2020-11-18 21:23 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +			throw('Item ' + itemID + ' is not a top-level attachment');
`throw` → `throw new Error` (that's why we can remove the function name)

2020-11-18 21:29 UTC, dstillman commented
Let's try this:

![mockup](https://user-images.githubusercontent.com/783082/99589744-71830580-29ba-11eb-817c-404486b30ded.png)

- Just the PDF as the title. "Create parent item for:" with a colon is a bit weird.
- I think "Create Empty Parent" → "Manual Entry" makes more sense. "Create Empty Parent" is technically more accurate — it's the creation of the empty item that's happening immediately — but we don't really say "Parent" without "Item", and "Manual Entry" makes it a little clearer what you're setting yourself up for by creating an empty item.
- Add `<?xml-stylesheet href="chrome://zotero-platform/content/overlay.css" type="text/css"?>` to get proper the font for the input box on macOS
- `font-size: 14px` for the input
- Slight change in order of identifiers in placeholder, and no colon
- Narrower width
- Align buttons with input box

2020-11-18 21:32 UTC, dstillman commented
Also, for what it's worth, we kind of gave up on the container/component split thing. If there's no compelling reason to keep that, it's fine to combine into just a component. In the past I've found it a little useful to develop a complicated component outside of Zotero, with nothing Zotero-specific in the component, but that's probably not necessary here.

2020-11-19 22:43 UTC, dstillman commented on chrome/content/zotero/components/createParent/createParent.jsx
> +import ReactDom from "react-dom";
`ReactDom` → `ReactDOM`

2020-11-20 07:24 UTC, dstillman commented
A few more things:

- Let's go with `padding: 20px 15px;` instead of `2em` for the dialog padding
- "to identify this item" → "to identify this file" — I guess this depends on whether you're identifying the file or identifying the parent item you're about to create, but given that you start with a file and we're putting the filename above the text box in bold, "file" seems more right to me
- We should disable the accept button when the input box is empty

2020-11-20 21:17 UTC, merged