Add items to collection via context menu
zotero/zotero pull request #2360
Opened 2022-02-17 23:27 UTC by AbeJellinek

Closes #37.

2022-02-17 23:39 UTC, dstillman commented
And we could consider having a Move option as well, as an accessible equivalent to [holding down Cmd/Shift](https://www.zotero.org/support/collections_and_tags#adding_items_to_collections).

2022-02-18 00:39 UTC, AbeJellinek commented
OK, see new commits. Would Move be a top-level submenu next to Add to Collection?

2022-02-18 00:43 UTC, dstillman commented
Yeah, but let's do without for the moment, since it's easy to accomplish the same thing without it. We can revisit if people really want it.

2022-02-20 17:13 UTC, dstillman requested changes

2022-02-20 17:13 UTC, dstillman commented on chrome/content/zotero/zoteroPane.xul
> +									<menuitem id="zotero-add-to-new-collection" label="&zotero.toolbar.newCollection.label;" oncommand="ZoteroPane_Local.addItemsToCollection(null, true)"/>
Oh, nice — but let's move this above the hierarchical tree. I have a ton of collections in my test library and didn't even notice this existed until I looked at the code

Also can note in the description that this closes https://github.com/zotero/zotero/issues/2069

2022-02-20 17:13 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +		if (createNew) {
Throw error (e.g., "collection must be null if createNew is true") if `collection` is not falsy

2022-02-20 17:13 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +	this.addItemsToCollection = async function (collection, createNew = false) {
→ `addSelectedItemsToCollection`

2022-02-20 17:13 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +		let separator = popup.querySelector('#zotero-add-to-collection-separator');
Might as well use `document.getElementById`

2022-02-20 17:13 UTC, dstillman commented on chrome/content/zotero/xpcom/utilities_internal.js
> +	 * @param {Zotero.Library|Zotero.Collection} Currently selected item (displays as checked)
Missing "currentTarget"

2022-02-22 00:36 UTC, merged