making toolbar accessible to the keyboard - initial conversion
zotero/zotero pull request #3188
Opened 2023-06-30 04:24 UTC by abaevbog

Initial work on converting [this commit](https://github.com/zotero/zotero/commit/d866a10a2b56e96631a1563572d3f2918f1f006a#diff-e82e5d43de73ef85cfc03f6402d5afb5c18a629850d689b1d764516b5cab98f3) for Zotero 7.
Addresses #3001

Here's the issue: I can't seem to find what this commit is initially supposed to do ...

As the name suggests, I assumed it makes it possible to get to `advanced search`, `new note`,` add attachment`, `new item` buttons via Tab. That commit was part of Zotero 6.0.26, so I expected it would be possible there but not in Zotero 7 without this change. 
However, the navigation via tab works for me the same exact way in Zotero 6.0.26 as it does in Zotero 7 beta - the toolbar buttons cannot be reached via Tab.  [This screenshot ](https://www.dropbox.com/s/mu9k1w9uhy42434/screenshot.png?dl=0) shows the fields that get visited by repeatedly hitting Tab for both Zotero versions. 

The buttons from the toolbar are accessible if I enable `Full Keyboard Access` on Mac but then the toolbar buttons are accessible in Zotero 7 without these changes. 

I must be missing something here.

2023-07-01 23:29 UTC, dstillman requested changes
This doesn't seem to be working right. From the quick search bar, the first Shift-Tab should focus the search bar's mode selector. The second Shift-Tab should focus New Collection. Here it seems to be skipping over the mode selector, but then Tab moves forward (correctly) to the mode selector.

2023-07-01 23:29 UTC, dstillman commented on chrome/content/zotero/elements/itemBox.js
> +			const last=tabbableFields[tabbableFields.length-1];
Make sure you have eslint set up. You removed spaces around the `=` and `-`, which should be flagged by eslint. (Lots of existing warnings in existing code, but new code should be correct.)

2023-07-01 23:29 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +    ev.getModifierState("Control") || ev.getModifierState("OS");
Fix indenting

2023-07-01 23:29 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +				&& event.originalTarget.id == "zotero-tb-search-menu-button") {
Restore indent

2023-07-01 23:29 UTC, dstillman commented on chrome/content/zotero/zoteroPane.js
> +				|| Zotero.rtl && event.key === 'ArrowLeft') {
Restore indent, here and below

2023-07-03 17:07 UTC, abaevbog commented
You are right. The search mode selector was moved into some kind of shadow DOM, so it wouldn't get recognized as an element that needs to be focused on. I added another special case for it to not get skipped on Shift-Tab from the search bar.

2023-07-05 07:17 UTC, merged